"""The answer recipes: turn a question spec into ordinary pipeline steps.

``_constants`` holds the tunables and result types, ``_common`` the shared helpers over the data model,
and ``_plan`` the planners, ``plan``, suggestion scoring and the editable chips. This module re-exports
the public surface, so ``dancr.core.recipes`` is unchanged for its callers.
"""
from ._constants import (
    RULES_VERSION,
    STAT_WORDS,
    STAT_CHOICES,
    EVERY_CHOICES,
    EVERY_WORDS,
    TOP_CHOICES,
    RECIPES,
    WEIGHT,
    NEAR_DEFAULT,
    EXPERIMENT_ROWS,
    TEST_CHOICES,
    GROUP_MAX,
    MAX_SUGGESTIONS,
    PlanError,
    Suggestion,
    AMOUNT_WORDS,
    READING_WORDS,
    MONEY_WORDS,
    CURRENCY_UNITS,
    PART_WORDS,
    QUANTITY_NAMES,
    PAIRED_WORDS,
    CELL_CHOICES,
    NEAR_CHOICES,
)
from ._common import (
    _col,
    plural,
    stat_title,
    label,
    _tlabel,
    groupables,
    _is_key,
    _usable_links,
    reachable,
    _members,
    _path,
    ordered_measures,
    default_stat,
    _tidy_number,
    _safe_spellings,
    _spelling_formula,
    _free_name,
    filter_text,
    _rule,
    auto_every,
    _asked_span,
    _bucket_stats,
    _bucket_name,
    _y_label,
    _span_text,
    group_label,
    _compare_every,
    _part_formula,
    top_n,
    row_noun,
    same_kind,
    _paired_names,
    _default_cell,
)
from ._plan import (
    PLANNERS,
    _Builder,
    _candidates,
    _condition_columns,
    _dedupe,
    _distinct,
    _score,
    apply_choice,
    breaks_of,
    chips,
    experiment,
    plan,
    suggest,
)
